### ISSUE TITLE
Plugin for addPageLayoutHandles breaks adding layouts from catalog_product_view_id_{{ID}}.xml files

### ISSUE THREAD

**Issue by Karol-Aniszewski** [magesuite/cache#6]
The plugin vendor/creativestyle/magesuite-cache/Plugin/Framework/View/Result/Page/RemoveEntityCache.php
added in 1.4.7 version of this module is breaking OOTB functionality of handling layouts by these files:

- catalog_product_view_id_{{ID}}.xml
  - eg. here: vendor/magento/module-catalog/Helper/Product/View.php:186
- catalog_category_view_id_{{ID}}.xml
  - eg. here: vendor/magento/module-catalog/Controller/Category/View.php:243

and probably in some other handlers.

The upgrade of this module was added to Magento 2.4.7-p3 upgrade, so it breaks above functionality for those how upgraded Magento.

It also impacts the OOTB Widgets functionality, when the admin wants to pick Products by IDs on which the eg. CMS Static Block should be displayed.

**Comment by piotrmatras** [comment]
@Karol-Aniszewski thanks for reporting this issue.
The latest version has a switcher in the admin configuration to disable this plugin.
`product_performance/cache/enable_layout_handle_for_entity` set this to 1.

**Comment by Karol-Aniszewski** [comment]
Thank you very much for the update and the code upgrade.
In which Magento (Adobe Commerce) version or security patch will it be available?

**Comment by piotrmatras** [comment]
@Karol-Aniszewski you don't need to update Magento version. Use `composer update`.  See more info: https://github.com/magesuite/cache/releases/tag/v1.4.8

**Comment by Karol-Aniszewski** [comment]
ok, I understand. I just wanted to minimize the effort of our team in the future.
In fact during development and deployment of Magento we don't use composer update to omit any conflicts between many modules depending on each other.
Anyway we can just update only the magesuite-cache module in our composer.json.

Thank you for effort ;)
